server: 
  port: 8088 
  session-timeout: 1800
  session-rememberMe: true

##activiti 不验证
security:
  basic: 
    enabled: false
    
spring:
  main:
    allow-bean-definition-overriding: true 
sys: 
  operation-log: 
    #系统操作日志同步还是异步存储(异步走mq)
    sync: true 
  initCache: true 
     
logging: 
  config: classpath:logback.xml
  path: E:/logs
