spring: 
  profiles: 
    active: dev 
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8 
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet: 
    multipart: 
      max-file-size: 2048MB 
      max-request-size: 2048MB
mybatis: 
  mapperLocations: classpath:/com/hy/dao/*.xml
  typeAliasesPackage: com.hy.entity
  mapperScanPackage: com.hy.dao
  configLocation: classpath:/mybatis/mybatis-config.xml 

#swagger title
swagger:
  title: cps 
